### ISSUE TITLE
stopwatch

### ISSUE THREAD

**Issue by abelRoland** [abelRoland/timer#2]
- [x] Investigate GitHub repo with stopwatch apps.
- [x] In branch `stopwatch`
- [x] Create a `stopwatch.js`

**Comment by adekimpianna** [comment]
guys @abelRoland @mametur I got a couple of them.

this one is my preference:

https://github.com/JamieMcGibbon/TechnicalCafe/blob/master/Misc%20Tutorials/Stopwatch%20Tutorial/script.js

but there are also these twos:

https://github.com/GeekLaunch/stopwatch/blob/master/stopwatch.js

https://gist.github.com/anonymous/fe5cdd7e9cd14fea796b27d19f8d1cb6


There is this stop, start and reset function for each of stopwatch js. Should i also included these functions on my js file? 
Or are we going to make these buttons/functions as the shared function? -->same start/stop/reset buttons for both timer and stopwatch

**Comment by abelRoland** [comment]
Hey @adekimpianna . Great. This first one really seems perfect. And it's very easy to integrate on our project I believe (we have the same two buttons). Now I just push the `index.html` so maybe if you want you can already work on it. 

About the buttons, on the `index.html` I put them as the same button for both functions, but maybe we should put separate, it's easy to change on the html file for me. Just let me know what you think about it.

Thanks.

**Comment by adekimpianna** [comment]
@abelRoland It sounds great if the same start/stop/reset buttons works for both timer and stopwatch (like what you do now), so it would be similar like the timer and stopwatch from Google 😄

**Comment by abelRoland** [comment]
Nice 👍
